apiVersion: v1 #Cria drive no Google Cloud Platform
kind: PersistentVolumeClaim
metadata:
    name: pvc-2
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
    storageClassName: slow  #Foi declarado no storage-class