apiVersion: apps/v1
kind: Deployment
metadata:
    name: database-deployment
spec:
    template:
        metadata:
            name: database
            labels:
                app: database
        spec:
            containers:
                -   name: database-container
                    image: aluracursos/mysql-db:1
                    ports:
                        -   containerPort: 3306
                    envFrom:
                        -   configMapRef:
                                name: db-configmap
    selector:
        matchLabels:
            app: database