apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
spec:
    replicas: 3
    template:
        metadata:
            name: frontend
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend-container
                  image: aluracursos/portal-noticias:1
                  ports:
                      - containerPort: 80
                  envFrom:
                      - configMapRef:
                            name: portal-configmap
    selector:
        matchLabels:
            app: frontend