apiVersion: v1
kind: Service
metadata:
    name: svc-backend
spec:
    type: NodePort
    selector:
        app: backend
    ports:
        - port: 80         #Porta do container
          nodePort: 30001  #Porta que chamarei no navegador