apiVersion: v1
kind: Service
metadata:
    name: svc-frontend
spec:
    type: NodePort
    selector:
        app: frontend
    ports:
        - port: 80         #Porta do container
          nodePort: 30000  #Porta que chamarei no navegador