apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: frontend-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: frontend-deployment
    minReplicas: 1      #Gerenciando as replicas
    maxReplicas: 10
    metrics:
        -   type: Resource
            resource:
                name: cpu
                target:
                    type: Utilization           #Baseado na utilização
                    averageUtilization: 50      #Chegando a mais de 50% de uso ele remove e cria outro