apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: frontend-replicaset
spec:
    template:
        metadata:
            name: frontend
            labels:
                app: frontend
        spec:
            containers:
                -   name: frontend-container
                    image: aluracursos/portal-noticias:1
                    ports:
                        - containerPort: 80
                    envFrom:
                        - configMapRef:
                              name: portal-configmap
    replicas: 3
    selector:
        matchLabels:
            app: frontend