apiVersion: v1
kind: Service
metadata:
    name: svc-pod-1
spec:
    type: NodePort
    selector:
        app: first-pod
    ports:
        - port: 80
          nodePort: 30000
          # nodePort: 30000-32767