apiVersion: v1
kind: Pod
metadata:
    name: backend
    labels:
        app: backend
spec:
    containers:
        - name: backend-container
          image: aluracursos/sistema-noticias:1
          ports:
              - containerPort: 80
          envFrom:
              - configMapRef:
                    name: system-configmap